# This is the main HUGO config file
# Note: Many examples online will use YAML (which uses `:') instead of toml. So
# watch out for copy and paste.

baseurl = "/"
languageCode = "en-us"
title = "André Rauh"
#title = "rauhs github"

footnotereturnlinkcontents = "↩"

# THe following is just a copy form the gohugo site:
#archetypedir=               "archetype"
# include content marked as draft
buildDrafts =              false 
# include content with datePublished in the future
buildFuture =              false
#canonifyUrls=               false
# config file (default is path/config.yaml|json|toml)
# config=                     "config.toml"    
# contentdir=                 "content"
# dataDir=                    "data"
# defaultExtension=           "html"
defaultLayout=              "news"
# filesystem path to write files to
# destination=                ""    
# disableLiveReload=          false
# Do not build RSS files
# disableRSS=                 false 
# Do not build Sitemap file since we have non-public pages:
disableSitemap = true
# edit new content with this editor, if provided
editor=                     "vim"
# footnoteAnchorPrefix=       ""
# footnoteReturnLinkContents= ""
# languageCode=               ""
# layoutdir=                  "layouts"
# Enable Logging
# log =                        false 
# Log File path (if set, logging enabled automatically)
# logFile=                    ""    
# "yaml", "toml", "json"
# metaDataFormat=             "toml" 
# newContentEditor=           ""
# Don't sync modification time of files
# noTimes=                    false 
# paginate=                   10
# paginatePath=               "page"
# permalinks=         
# Pluralize titles in lists using inflect
# pluralizeListTitles=         true 
publishdir=                 "public"
# color-codes for highlighting derived from this style
pygmentsStyle=              "monokai"
# true= use pygments-css or false= color-codes directly
# Seems to not work...
pygmentsUseClasses =        true
# sitemap=                    ""
# filesystem path to read files relative from 
# source=                     ""    
# staticdir=                  "static"
# display memory and timing of different steps of the program
# stepAnalysis=               false 
# theme to use (located in /themes/THEMENAME/)
# theme=                      ""    
# title=                      ""
# if true, use /filename.html instead of /filename/
# uglyUrls =                  false
# verbose output
#verbose =                   true
# verbose logging
# verboseLog=                 false 
# watch filesystem for changes and recreate as needed
#watch=                      true

[taxonomies]
  category = "categories"
  tag = "tags"

# The Markdown config
[blackfriday]
  angledQuotes = true
  fractions = false
  plainIdAnchors = true
  extensions = ["fencedCode", "tables", "autolink", "footnotes"]
# Extensions can be:
# "noIntraEmphasis" "tables" "fencedCode" "autolink" "strikethrough"
# "laxHtmlBlocks" "spaceHeaders" "hardLineBreak" "tabSizeEight" "footnotes"
# "noEmptyLineBeforeBlock" "headerIds" "titleblock" "autoHeaderIds"
# See: https://github.com/russross/blackfriday

# Sitewide variables available in the templates:
# Then available as
# .Site.Params.MyUser
[params]
  XY = "Foo"

# Define the order of the menu here:
# A lower weight will mean it appears first!
[[menu.docs]]
    name = "General"
    weight = -200
[[menu.docs]]
    name = "Services"
    weight = -100
[[menu.docs]]
    name = "Other"
    weight = -10

